### ISSUE TITLE
Criação do Servidor da Aplicação

### ISSUE THREAD

**Issue by luiscarlossf** [luiscarlossf/get-promo#28]
A criação do servidor inclui, a aplicação node.js e o projeto de banco de dados (O diagrama de classes está na Wiki).

**Comment by gavelino** [comment]
Não seria o projeto do sistema servidor (feito em Node.js)? O BD não é apenas uma parte do problema?

**Comment by wesleyrafael** [comment]
Servidor com funcionalidades básicas criado. Falta somente adicionar as funcionalidades da terceira iteração.
